import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className='container mx-auto'>
        <nav>
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about-us">Avout Us</a>
        </nav>
      </header>
      <main className={styles.main}>
        <div className='grid'>
          <a href="" className='py-5'>
            <img />
            <h2>Event in Hanoi</h2>
            <p>
              There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.
            </p>
          </a>
          <a href="" className='py-5'>
            <img />
            <h2>Event in Danang</h2>
            <p>
              There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.
            </p>
          </a>
          <a href="" className='py-5'>
            <img />
            <h2>Event in Hochiminh Cty</h2>
            <p>
              There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}


export function getServerSideProps() {
  return {
    props: {
      title: 'Hello word!'
    }
  }
}